### ISSUE TITLE
New rich editor (Froala) strips out empty <i> tag

### ISSUE THREAD

**Issue by Verbat** [octobercms/october#2108]
I'm using the new rich editor (build 345) and included the "italics" tag "i" at the allowed empty tags section, which is accessible via the settings page, but my setting is ignored. 

The following:
`<div class="item"><i class="right triangle icon"></i> Item 1</div>`
always becomes
`<div class="item">Item 1</div>`

Is this intended (if so can I avoid this issue) or a bug?

**Comment by Benpxpx** [comment]
```<p>Test sentence <i class="fa fa-cal"></i></p>```

This doesn't get stripped for me, see if putting a `&nbsp;` in there stops it from being stripped for you.

**Comment by jeremymouton** [comment]
Another workaround would be to use a `<span>` tag instead. 

`<i>` stands for "Italics" and since this is in a WYSIWYG with an italics option, I would want empty `<i>` tags to be removed.

**Comment by Verbat** [comment]
Did some further test.

The following works
`<div class="item"><i class="fa fa-cal"></i> Test sentence</div>`

This does not work. If the first css class "fa" is removed the complete i tag gets stripped
`<div class="item"><i class="fa-cal"></i> Test sentence</div>`

Workaround is as Benpxpx already mentioned to use a `&nbsp;`
This works
`<div class="item"><i class="fa-cal">&nbsp;</i> Test sentence</div>`

Unfortunately using spans is not a option for me as semantic-ui uses `<i>` for all icons.
For now i think i can use the `&nbsp;` to avoid this behavour but i still think it's not an intended behavior.

**Comment by Benpxpx** [comment]
> This does not work. If the first css class "fa" is removed the complete i tag gets stripped
> `<div class="item"><i class="fa-cal"></i> Test sentence</div>`
Just tried this myself, and the i element is being stripped for me as well. A WYSIWYG is a finicky at the best of times.

Glad the work around done the trick, hopefully this use case can be resolved in the future.

**Comment by daftspunk** [comment]
Settings > Editor settings > Markup tags > Allowed empty tags

Add `i.fa` to this textarea and save.

**Comment by claudchan** [comment]
Hi,
Settings > Editor settings > Markup tags > Allowed empty tags is still not working. Can confirm?

**Comment by tombien** [comment]
Hello, I have built 419 and it still not working. I have `i` in Allowed empty tags and editor always clean it.

**Comment by LukeTowers** [comment]
@tombien did you add `i.fa` like @daftspunk [said](https://github.com/octobercms/october/issues/2108#issuecomment-224706494)?

**Comment by tombien** [comment]
I have another icon for our customer. We have classes zi, zi-... So I made it like for fa, it doesnt work. Now I try wit fa classes - it works. You made it only for Font Awsome Icons :) ?

**Comment by LukeTowers** [comment]
I'm not sure, did you try `i.zi` as well?

**Comment by tombien** [comment]
I hope yes. I have this in empty tags
`textarea, a, iframe, object, video, style, script, i.zi`

**Comment by LukeTowers** [comment]
Hmm, it should be working then.

**Comment by tombien** [comment]
.fa class works when I have in empty tags i.zi or whatever.... also if I dont have i in empty tags.
but another class then .fa doesnt work anytime.

**Comment by tombien** [comment]
I can make screen video, if you want.

**Comment by igor-tv** [comment]
> I have another icon font for our customer. We have classes like .zi, .zi-... So I made it like for .fa, it doesnt work. Now I try it with .fa classes - it works. You made it only for Font Awsome Icons :) ?

I confirm this. This only works for` i.fa`. For other tags and classes does not work, empty tags are deleted when saved. I wanted to add `span.iconify` to the allowed empty tags, but that didn't help. Have to add `&nbsp;` inside.

October 465

**Comment by tombien** [comment]
@igor-tv 
This is still not fixed. I can confirm it. October 465. I mentioned this 3 years ago :)

I can put to Froala `<i class="fa fa-bulb"></i>` and it will stay.
I can put `<i class="xx xx-bulb"></i>` and it will not stay.

I have `<i>` in my allowed empty tags.
Class "fa" do not need allowed empty tags - it stays always with or without allowed empty `<i>`

I know, this is not a "big problem" but we use custom icon fonts, not always Font Awesome. And sometimes it is useful to let our customer to use some icons thru css classes in Froala.

**Comment by jeremymouton** [comment]
@tombien 3 years and you're still using <i> for icons? :)

**Comment by tombien** [comment]
Hi,
yes in some cases.
for example Font Awesome docs still use it:
https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use <https://fontawesome.com/how-to-use/on-the-web/referencing-icons/basic-use>

 And yes I think it is useful for our customers - normal people which can write for example blog post using Froala Editor. And they can put <i> (this is a button in toolbar)
 and they can put a css class „fa fa-whatever“ to this <i> :)

**Comment by tombien** [comment]
But this is not the problem. This bug is also for span.
You can put <span class=„fa fa-whatever“></span> but you can not put <span class=„zi zi-whatever“></span> - only fa class is accepted - this is the problem - if you have a custom icon font.

**Comment by bennothommo** [comment]
@tombien If you want this issue to be given priority over others, please consider [placing a bounty](https://www.bountysource.com/issues/34976424-new-rich-editor-froala-strips-out-empty-i-tag) on it.

**Comment by LukeTowers** [comment]
@tombien @igor-tv @claudchan Can you test #5126?

**Comment by igor-tv** [comment]
> @tombien @igor-tv @claudchan Can you test #5126?

This works for me on a clean project. But on a live project, after replacing files with new ones from PR, the toolbar stopped showing in the editor. There may be some conflict with already installed plugins or with existing editor settings.

<img width="1002" alt="Снимок экрана 2020-06-15 в 02 23 53" src="https://user-images.githubusercontent.com/6777469/84606613-2d8e5080-aeb0-11ea-8644-d38a355b1533.png">

**Comment by igor-tv** [comment]
I had a rule for allowed empty tags.
`i.fa, i.fas, i.far, i.fab,`
When I removed it, everything worked as it should.

**Comment by LukeTowers** [comment]
@RomainMazB could you investigate why that broke things?

**Comment by chocolata** [comment]
Hi @daftspunk,

Could it be that this issue is still present in the editor? Whenever I try to add a Font Awesome icon in the editor via the code view, it just gets removed.

Example: 
`<i class="fa-solid fa-right-long"></i>`

... is dropped right away upon save. I've tried the above options, but to no avail. These are my editor settings:

![image](https://user-images.githubusercontent.com/3584586/162795602-6f40d820-ef12-4ff2-b626-af56d5de1d69.png)

Do you see anything that might cause the issue? Thanks for looking into this.
