### ISSUE TITLE
The loading text not show properly

### ISSUE THREAD

**Issue by gergo85** [octobercms/october#3792]
##### Actual behavior
![ezgif-3-7aa12aa85b](https://user-images.githubusercontent.com/2959112/45621757-bed55680-ba81-11e8-9936-dc72942f614f.gif)

##### Reproduce steps
Click on the Refresh button in the log pages.

##### October build
442

**Comment by w20k** [comment]
Seems like past fixes did something wrong :) 

https://github.com/octobercms/october/pull/3394

**Comment by Eoler** [comment]
It works when buttons are in a wrapper div.loading-indicator-container (form buttons), but not in a toolbar...

**Comment by LukeTowers** [comment]
@gergo85 @w20k @Eoler can one of you make a PR to fix it?

**Comment by w20k** [comment]
@LukeTowers , will do it tomorrow, if @gergo85 or @Eoler have time today to create PR;

Seems like #3394 should be reverted, and that would fix the problem: 
File: https://github.com/octobercms/october/blob/8f713ed881a3429f5c09530e20be74fa9783f968/modules/system/assets/ui/less/loader.less
Append: 'background: @body-bg;' to .loading-indicator { .. }

**Comment by LukeTowers** [comment]
Probably #3394 and it's follow up PR should be fixed and then a more specific fix for the original #3394 issue to remove the background in that specific case should be applied.

**Comment by LukeTowers** [comment]
@w20k it's still applicable, #3394 was for a custom background of solid white, I don't think it was for any built in stuff. @Alex360hd could you comment on this?

**Comment by w20k** [comment]
@LukeTowers , I'm not 100% sure, but what I've found out, it won't work with transparent or any inherited option. 
Seems like there was one more change, in css, that removed the default background color from the component or something else :)
Right now, in admin panel, main background color is set on the 'body' element.

I could suggest one fix, like @ayumihamsaki did with the form-button ([PR #3576](https://github.com/octobercms/october/pull/3576)), by adding data-attribute => ' [data-control="toolbar"] .loading-indicator' .

**Comment by Alex360hd** [comment]
For what I remember, I just removed the background color of the wrapper. But maybe on this page, that background recovered all the buttons, letting some spaces to display the loading text correctly.

2 solutions : 
- Easiest : You can rollback my commit in order to reuse the @body-bg color as an overlay for the buttons. It will work as before, keeping the background color problem described on my PR.
- Average : We could find another element to copy background color, maybe there is something more logic than @body-bg that could stay grey when you are on the grey background and white when you are on a white background
- More difficult, but more elegant to me : Actually, when you click on the refresh button, it add a div with a position:absolute containing the loading text. In terms of UI, I think it would be better to directly replace the text of the button during the loading (and also disable the button during the loading to avoid multiple click).

**Comment by w20k** [comment]
@Alex360hd , It's already work this way ("More difficult"). The only issue is background color, right now it's set to none;

![sep-18-2018 11-02-31](https://user-images.githubusercontent.com/1053320/45673087-7629a600-bb32-11e8-9434-127af8d27338.gif)

**Comment by LukeTowers** [comment]
I'm thinking we should revert the original PR that caused this (and the PR that patch fixed it in only one spot and then we should revisit a better approach for fixing the original issue @w20k @Alex360hd

**Comment by w20k** [comment]
@LukeTowers, did it - #3840
