### ISSUE TITLE
SameSite Cookie not working

### ISSUE THREAD

**Issue by ghost** [octobercms/october#3893]
Today I upgraded my October CMS to PHP 7.3

I done the following things:

1. Add the following code to my .HTaccess

`AddHandler application/x-httpd-php73 .php .php5 .php4 .php3`

2. Updated the Version in the Cpanel

3. Says this in the admin backend dashboard:

![1](https://user-images.githubusercontent.com/17784082/47530809-2e1d4200-d89b-11e8-8edd-e78ee2f095d3.png)

4. I have added these three lines of code inside my .HTaccess

```
Header always edit Set-Cookie (.*) "$1; HTTPOnly"
Header always edit Set-Cookie (.*) "$1; Secure"
Header always edit Set-Cookie (.*) "$1; SameSite"
```

5. Session Config File, I have added the following code at the bottom as per PR https://github.com/octobercms/october/pull/3688

```
    /*
    |--------------------------------------------------------------------------
    | Same-Site Cookies
    |--------------------------------------------------------------------------
    |
    | This option determines how your cookies behave when cross-site requests
    | take place, and can be used to mitigate CSRF attacks. By default, we
    | do not enable this as other CSRF protection services are in place.
    |
    | Supported: "lax", "strict"
    |
    */
    'same_site' => 'strict',
];
```

## Testing and NOT Working

I am expecting the October Session Cookie to have two ticks and say 'Strict' for the HTTPonly, Secure and SameSite:

![2](https://user-images.githubusercontent.com/17784082/47531687-da602800-d89d-11e8-9b27-d85eaf6a0fef.png)

Also an extra screenshot showing that I do have SameSite Turned on:

![3](https://user-images.githubusercontent.com/17784082/47531889-578b9d00-d89e-11e8-83ca-f997bf96ec78.png)

Therefore I think it is NOT working and there is an error somewhere or maybe I have not fully correctly set it up! But I am pretty sure I have turned it on correctly my side.

**Comment by ayumihamsaki** [comment]
## Update:

Adding the following code to the .HTaccess makes it work:

`Header always edit Set-Cookie (.*) "$1; HTTPOnly; Secure; SameSite=Strict"`

See screenshot:

![4](https://user-images.githubusercontent.com/17784082/47533627-fff03000-d8a3-11e8-895a-fb5e25121ceb.png)

However, this just highlights that the code in the `session.php` is not working!

**Comment by Teranode** [comment]
Hmm,
Since you have php 7.3 can you remove the htaccess headers.

- go into a plugin create a routes.php file 
- add a random route
- add the `web` middleware to it and then go to that route to check the cookie flag?

**Comment by ayumihamsaki** [comment]
@Teranode 

Ok just did exactly what you said and the flag is:

![2018](https://user-images.githubusercontent.com/17784082/47538417-b0692e80-d8ba-11e8-9919-46eaa48d6874.png)

**Comment by Teranode** [comment]
@ayumihamsaki the header should be set by the SessionStart class in the web middleware and the CMS controller and Backend Controller utilize the web middleware so maybe try deleting cookies then refreshing

**Comment by ayumihamsaki** [comment]
@Teranode 

First thanks for your advice. I understand that Laravel 5.5 or greater combined with PHP 7.3 will have the SameSite Cookie.

I believe the issue is not with regards to them, the issue is with regards to October CMS URL system. I will show you steps to repeat the issue (stepping up a static webpage in october)

## Steps to Repeat Issue

1. I removed the `.HTaccess` headers to try and force any cookie headers

2. I added the `session.php` config details:

```
    /*
    |--------------------------------------------------------------------------
    | Same-Site Cookies
    |--------------------------------------------------------------------------
    |
    | This option determines how your cookies behave when cross-site requests
    | take place, and can be used to mitigate CSRF attacks. By default, we
    | do not enable this as other CSRF protection services are in place.
    |
    | Supported: "lax", "strict"
    |
    */
    'same_site' => 'strict',
];
```

3. I create a Static webpage using October's URL system, see screenshot:

![1](https://user-images.githubusercontent.com/17784082/47567839-14254300-d91f-11e8-8fc8-cef3fd667107.png)

4. I test the Static page in Google Chrome Dev Tools, see screenshot:

![2](https://user-images.githubusercontent.com/17784082/47567878-2901d680-d91f-11e8-8ea2-4d47678939a0.png)

As you can see the 'Strict' flag is not showing.

I believe October should add the Middleware to it's URL system and have the SameSite flag working automatically without the need for the developer to have to add the middleware route.

(I hope I explained the issue)

**Comment by LukeTowers** [comment]
@ayumihamsaki in theory it's already implemented is what @Teranode is saying

**Comment by ayumihamsaki** [comment]
Thanks Luke for clearing that up, I was wondering that. I guess I will just have to wait for PHP 7.3 to come out for more people to confirm this bug.

**Comment by ayumihamsaki** [comment]
Thanks Luke for clearing that up, I was wondering that (it did have me a little confused). I guess I will just have to wait for PHP 7.3 to roll out to more hosting comnpanies - for more people to confirm this bug.

**Comment by ayumihamsaki** [comment]
Thanks Luke for clearing that up, I was wondering that (it did have me a little confused). I guess I will just have to wait for PHP 7.3 to roll out to more hosting companies - for more people to confirm this bug.

**Comment by Teranode** [comment]
Just added PHP 7.3 on my local machine and im not getting the same issues you are:
![](https://i.imgur.com/qo8Bo00.png)
![](https://i.imgur.com/nB6Ijbh.png)

**Comment by ayumihamsaki** [comment]
Will investigate over the weekend - hopefully can find the reason and not just end up doing a brand new install to try and correct the issue.

**Comment by ayumihamsaki** [comment]
I done a fresh new install (same issue)

1. phpinfo:

![1](https://user-images.githubusercontent.com/17784082/47606206-30e57780-da00-11e8-831b-352829a8dbd7.png)

2. HTaccess file, I took from here: https://github.com/octobercms/october/blob/master/.htaccess

3. I downloaded the zip file from octobercms.com and uploaded to the server

4. changed session.php to this:

![3](https://user-images.githubusercontent.com/17784082/47606228-79049a00-da00-11e8-9925-692a0bc2845c.png)

5. Checked on the homepage of a brand new install and looks like this:

![2](https://user-images.githubusercontent.com/17784082/47606231-86ba1f80-da00-11e8-915f-096490dcbfb4.png)

Really not sure what the issue is ?

**Comment by ayumihamsaki** [comment]
re-test php version: 7.3.6 as of 05-07-2019, see test results:

![test-pix](https://user-images.githubusercontent.com/17784082/60723907-dc9a7c00-9f2c-11e9-9231-8adda74146c4.png)

**Comment by nathan-van-der-werf** [comment]
I'm also running OctoberCMS with CloudFlare on PHP 7.3, I'm not having these problems.

**Comment by ayumihamsaki** [comment]
Going to investigate this further, I have found the Laravel PR, see here: https://github.com/laravel/framework/pull/18036/files

Will do some further investigating on it.

Please note, I quote someone from the Laravel team talking about this:

> Yes it seems they just accepted the PR and never checked if it actually worked. A bit sloppy...

**Comment by ayumihamsaki** [comment]
After a few hours researching I have the following conclusion. This is fixed in the following versions: Laravel 5.6.38 and Symphony 4.1.5.

Upgrading to Laravel LTS 5.9 should fix this.

**Comment by ayumihamsaki** [comment]
After a few hours researching I have the following conclusion. This is fixed in the following versions: Laravel 5.6.38 and Symphony 4.1.5.

Symphony PR: https://github.com/symfony/symfony/pull/27885
Laravel PR: Don't have the exact link (but speaking to team members in their repo that's their answer)

Upgrading to Laravel LTS 5.9 should fix this.

**Comment by LukeTowers** [comment]
Will be fixed by https://github.com/octobercms/october/issues/4381

**Comment by ayumi-cloud** [comment]
@LukeTowers This is working now as of v462, you can close this issue also maybe you want to remove it from your 1st comment list found here: https://github.com/octobercms/october/issues/4381#issue-455036703

**Comment by ayumi-cloud** [comment]
Note: Issue with Windows 10 and SameSite Google Chrome V80, users need to install KB4534273

See here for link: https://support.microsoft.com/en-gb/help/4534273/windows-10-update-kb4534273

**Comment by noiarek** [comment]
I'm still having this problem.

I did the same, I added the variable to `session.php` but the value is not lax on Chrome.

I'm currently using PHP 7.3.0 and October CMS 464.

Am I the only one experiencing this problem?

Cheers
