### ISSUE TITLE
Backend pages wont open for new administrators

### ISSUE THREAD

**Issue by Morsusy2k** [octobercms/october#4048]
- OctoberCMS Build: 446
- PHP Version: 7.2.10
- Database Engine: Mysql
- Plugins Installed: October Demo, RedirectToHTTPS

### Description:
Newly created administrators have trouble accessing pages in the backend.

### Steps To Reproduce:
- Created new administrator from CMS as a Developer with Super User.
- Login with new administrator account.
- Browse to CMS -> Pages
- Clicking on a page name does absolutely nothing.
- Checking any checkbox next to page names (ones for multiple deleting) fixes the problem.
- Inspecting the page shows following errors:
`Uncaught TypeError: Cannot read property 'setActiveItem' of undefined
jquery.min.js?v446:2 jQuery.Deferred exception: Cannot read property 'setActiveItem' of undefined TypeError: Cannot read property 'setActiveItem' of undefined
Uncaught TypeError: Cannot read property 'goTo' of undefined`
![Console screenshot](https://user-images.githubusercontent.com/27859457/51005848-d52b8480-1540-11e9-9db6-f48043ff9604.jpg)

**Comment by LukeTowers** [comment]
@Morsusy2k did you try deleting the cache and performing a hard reload in Chrome? (Right click on the reload button when the inspector is open)

**Comment by Morsusy2k** [comment]
@LukeTowers Yes, tried everything that came to mind. (same thing happens with my local environment and on the live too)
Tried on other PC (on which I have never loaded the site) same thing happens.

**Comment by LukeTowers** [comment]
@Morsusy2k does this happen with the RedirectToHTTPS plugin removed?

**Comment by Morsusy2k** [comment]
@LukeTowers Removed all plugins on local environment the problem is still there.

**Comment by LukeTowers** [comment]
Weird. @w20k could you look into this when you have a chance?

**Comment by therealfly** [comment]
I have the same problem. CMS is totally unusable ATM.

**Comment by w20k** [comment]
@LukeTowers, will look at it, today.

**Comment by Morsusy2k** [comment]
@w20k Just tried recompiling assets no change to the issue.
There is nothing that indicates unsafe scripts :/

**Comment by w20k** [comment]
@Morsusy2k, quick quest. Could you zip your application? Remove all configs or .env files and post a link here? Or make a repo with your setup. 
Will try to find the cause then.

**Comment by therealfly** [comment]
Hi Denis,

I will but it will be in 12 hours (different timezone) its running on a local machine at work so i will do it.

Greetings from the Netherlands

Johan

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Rike-cz** [comment]
I have same problem. @w20k Are you using "disable cache" in DevTools? When cache is disabled, there is no error. When you enable it, first reading of CMS or staticPages is ok, second and other triggers error.
Problem is [this line](https://github.com/octobercms/october/blob/2dbc56aead2ef2355135349b83860457f48f6235/modules/backend/assets/js/october.sidepaneltab.js#L171), something destroy $.oc.sideNav object (or is not created) actually.

**Comment by w20k** [comment]
@Morsusy2k, @Rike-cz - monkey patch v0.5; Try using the old jquery, seems like, there is a bug in the code related to the new version.
Will inform you fellows, when the fix will be on the way.

For now use: `https://code.jquery.com/jquery-2.2.4.min.js`

**Comment by Morsusy2k** [comment]
@w20k I am glad that there is an idea of where the problem is. Thank you so much for looking into this. Can you point us newbs out to how can we change core jQuery version?

**Comment by w20k** [comment]
@Morsusy2k, just paste the code to `modules/backend/asstes/js/vendor/jquery.min.js`. Worked for me...might be something, else for you. Test it with your build and comment, if it worked.
Thanks!

**Comment by Morsusy2k** [comment]
@w20k Hmm the error changed:
`Uncaught TypeError: e.event.addProp is not a function`
![Console screenshot](https://user-images.githubusercontent.com/27859457/51078199-09728280-16b2-11e9-962b-ca4f7067f6ac.png)

And not even the checkbox 'workaround' works anymore, not even + Add button.

**Comment by w20k** [comment]
@Morsusy2k, forgot one more thing 😄Remove everything from migrate.
`modules/backend/asstes/js/vendor/jquery-migrate.min.js`

**Comment by Morsusy2k** [comment]
@w20k It works! Are there any side effects? If I update the CMS does this get overridden? 
Thank you so much. Great support. :D

**Comment by w20k** [comment]
@Morsusy2k it will. That's why it's called `monkey patch` 😄
Don't think so.

I'll dig deeper to get this working in the next release - no worries.

**Comment by Rike-cz** [comment]
@w20k Works for me to! Thanks a lot!

**Comment by tobias-kuendig** [comment]
I'm having a similar issue on a fresh installation of build 446. Chrome behaves pretty strange. When trying to edit a cms page I get the following error:

![image](https://user-images.githubusercontent.com/8600029/51785358-ef777c00-2156-11e9-8172-52a7444b2051.png)

After reloading the page with Ctrl + F5 everything works. On the next page load however the problem occurs again until I hit Ctrl + F5.

I also had a customer call in that was unable to edit a static page in Edge. It was also on build 446 that was updated a few days earlier.

**Comment by w20k** [comment]
@tobias-kuendig you could downgrade jquery to 2.x version and remove jquery-migrate.

The only thing that I've found if you change this line (october.sidepaneltab.js):
```
// DATA-API
    // ============

    $(window).on('load', function() {
        $('[data-control=layout-sidepanel]').sidePanelTab()
    })

``` 
To
```
// DATA-API
    // ============

    $(document).ready(function() {
        $('[data-control=layout-sidepanel]').sidePanelTab()
    })

``` 
It starts working again... Not a best possible solution and 99% could break something else 😄

**Comment by adrenth** [comment]
Hi @w20k, any updates on this issue?

Have a lot of IE users complaining over here ;-)

**Comment by w20k** [comment]
@adrenth don't think it's related to IE, might be a different issue :) 

Have you tried my monkey patch (^see my comments)?

**Comment by adrenth** [comment]
Thanks for your quick response. Figured the source of this issue might be related to the recent updated libraries.

Currently downloading a Windows 7 image with IE 11 pre-installed. This is a setup from one of our clients which reported the issue to us.

Will try the monkey fix. And let you know my findings.

**Comment by w20k** [comment]
@adrenth thanks a lot for a quick response, as well :) 
If there would be active testers (don't use CMS a lot, lately). I might try out few fixes, but didn't have time to continue, yet.

This fix might work... but could cause other issues.
The only thing that I've found if you change this line (october.sidepaneltab.js):
```
// DATA-API
    // ============

    $(window).on('load', function() {
        $('[data-control=layout-sidepanel]').sidePanelTab()
    })

``` 
To
```
// DATA-API
    // ============

    $(document).ready(function() {
        $('[data-control=layout-sidepanel]').sidePanelTab()
    })

```

**Comment by adrenth** [comment]
@w20k I can confirm it works, I changed the `october.sidepaneltab.js` and it worked. So this is definately a `monkey fix` ;-)

However:

* `$(window).on('load')` works on IE Edge
* `$(window).on('load')` **does not work** on IE 11 (Windows 7)

* `$(document).ready()` do work on IE Edge and IE 11

**Comment by w20k** [comment]
@adrenth You could try clearing the cache and refreshing the page with "ctrl | cmd + r".
And don't use an option in dev tools: `Disable cache...`. Something related to the cache.

**Comment by adrenth** [comment]
At first I couldn't get it to work on IE11 (Win 7), other browsers seem to work fine.

1) I tried clearing the cache using the Developer Tools in IE11, did not see any 304 requests, only 200. 
2) Reloaded the page and it didn't work.
3) Requested another page in the backend and then navigated back to `/backend/rainlab/pages/` and then it worked.

**Comment by LukeTowers** [comment]
What's the recommend course of action here?

**Comment by w20k** [comment]
@LukeTowers will look at it once again, at the end of the week. And comment, what would be the best option to fix it.

**Comment by adrenth** [comment]
Hi @w20k, hope you are doing well. Any progress on this issue?

**Comment by w20k** [comment]
Hi @adrenth, sadly - nope. But hopefully will have a minute to deal with that on weekends.

**Comment by mjauvin** [comment]
@w20k tried your monkey patch and it's not working for me on Qutebrowser or Qupzilla.

In all cases (with or without your patch), forcing the page reload (ctrl-shift-r) allows the pages to be opened. When I move to a different backend menu and comeback, it breaks again until I force the page refresh...

**Comment by w20k** [comment]
@mjauvin have you tried both patches?

First, is to replace jQuery back to 2.x and remove content from `jquery-migrate.min.js `.
Second, is to use `$(document).ready..`.

**Comment by mjauvin** [comment]
@w20k I confirm, reverting back to jquery 2.2.4 and removing jquery-migrate does solve the problem.

**Comment by w20k** [comment]
@ayumihamsaki what do you think about this issue? Any ideas, why 3.x version does the loading of window differently (or maybe caches, or faster 😄)

**Comment by ayumihamsaki** [comment]
@w20k just had a quick read through. This is the first I heard about this issue (I don't use Rainlab Pages Plugin - I created my own plugins). Ah you said the words **caching** and that **october.sidepaneltab.js** both I complained about months ago. Just don't say about drag n drop tabs!

I find some things strange in the above comments though.

1. Morsusy2k was trying to use two different versions of jquery migrate at the same time, you should not use the 3.0.0+ version use the 3.0.1 only.

2. adrenth is saying Edge works but not IE11, did you look at the Modernizr Upgrade as **october.sidepaneltab.js** uses it quite heavily and as there is an issue with browsers that may be an issue as well.

* `$(window).on('load')` works on IE Edge
* `$(window).on('load')` **does not work** on IE 11 (Windows 7)
* `$(document).ready()` do work on IE Edge and IE 11

My thoughts would be to check the Modernizr and update the october.sidepaneltab.js

Ok that's my thoughts but I not even looked at any code yet. I can take a look in a few days time, right now just in the middle of coding something quite large.

**Comment by w20k** [comment]
It's too stupid to be true... 😄
@tobias-kuendig - your's FF bug could be fixed with single line of code. If you could test this out would be awesome ;)

File: `october.sidenav.js`
Change this
```$(document).ready(function(){
        $('[data-control="sidenav"]').sideNav()
    })```

To this:
```$(window).on('load', function(){
        $('[data-control="sidenav"]').sideNav()
    })```

**Comment by ayumihamsaki** [comment]
If it's ok I would like to give some advice on Browsers (after reading some people comments here).

I think October CMS should focus on "**ever-green browsers**" only. An ever-green browser is a modern browser which auto-updates.

The best Browser that has the highest support for the most number of API's is Google Canary (which is currently running Chrome V74).

Desktop Computers: Chrome 71.58% and Firefox 8.72% control most the world wide market share.

Mobile Devices: Chrome  56.74% and Safari 21.29% control most the world wide market share.

So you should focus mostly on these browsers!

IE11 is a dead / old browser and I would actually tell my clients not to use that browser and also to expect bugs using it with October CMS. I would also not expect the developers of October CMS to make their CMS work 100% with that browser.

Qutebrowser or Qupzilla I never heard of before and looked them up. Qupzilla is a completely dead project and you can buy their website. Qutebrowser is not an ever-green borwser and I would not recommend using it.

Personally I use Google Canary to build my October CMS websites due to using the latest API's.

For testing I use:

- Google Canary
- Google Chrome
- Firefox Nightly
- Opera Dev
- Safari IOS and MAC various versions
- UC Browser
- Edge
- Samsung Browser
- And IE11 on a basic level. IE 10 and below I have completely dropped now due to such low usage. IE11 I will soon drop in the near future as well.

**One last thing**: Safari is junk - it's like the new Internet Explorer and most of your bugs and issues will be on that browser. Note the Safari Browser on a MAC and on an Apple ipad IOS for example give a huge difference in annoying bugs.

Anyway, that's my thoughts and advice on Browsers using October CMS.

If you follow my advice and do w20k patch then you should get a problem with this issue. That's my thoughts anyway.

**Comment by tobias-kuendig** [comment]
@w20k, patching `./modules/backend/assets/js/october.sidenav.js` and running `php artisan october:util compile js` seems to fix the issue :+1:

**Comment by marcomessa** [comment]
> @w20k, patching `./modules/backend/assets/js/october.sidenav.js` and running `php artisan october:util compile js` seems to fix the issue in Firefox 👍

I confirm this is working with FF dev. Thank you!

**Comment by LukeTowers** [comment]
@w20k is that a fix that can be implemented in core? Does it break anything else? Does it require changing the jQuery version?

**Comment by mjauvin** [comment]
@w20k applied your fix - https://github.com/octobercms/october/issues/4048#issuecomment-464681943 to `sidepaneltab.js` and recompiled the js assets (`php artisan october:util compile js`) and it fixes the problem.

**Comment by Rike-cz** [comment]
@w20k Fixed in Opera too!

**Comment by w20k** [comment]
@LukeTowers yes it is for the core. Not sure, I hope it doesn't, but will run more tests. What it does, It changes the loading order of sidenav. So that it would be loaded at the same time as a sidebar. 
Nope - nothing to do with our JQuery upgrade.

Will make a PR.

**Comment by damianlewis** [comment]
Having the same issue with Chrome 72 and IE 11 on Windows 7 Enterprise but don't have this issue with Chrome 72 on Mac.

Reverting back to jquery 2.2.4 and removing jquery-migrate code does solve the problem for Windows.

**Comment by w20k** [comment]
@damianlewis - what about this fix https://github.com/octobercms/october/issues/4048#issuecomment-468933242?

**Comment by damianlewis** [comment]
@w20k Fix #4048 worked on Chrome but didn't resolve the issue for IE 11. I've reverted back to the original fix.

**Comment by w20k** [comment]
That's sad, can't test with IE11 😄 Need to find a hack for that!

**Comment by adrenth** [comment]
@w20k You could download a free Windows image from Microsoft site: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by w20k** [comment]
Thanks for a tip @adrenth!

**Comment by tfprado** [comment]
> It's too stupid to be true... 😄
> @tobias-kuendig - your's FF bug could be fixed with single line of code. If you could test this out would be awesome ;)
> 
> File: `october.sidenav.js`
> Change this
> 
> ```
> $(document).ready(function(){
>         $('[data-control="sidenav"]').sideNav()
> })
> ```
> 
> To this:
> 
> ```
> $(window).on('load', function(){
>         $('[data-control="sidenav"]').sideNav()
> })
> ```
> 
> Cant' reproduce in the latest dev build the same issue with chrome and new users... Hm...Any testers to help me out? :)

@w20k I am at October build 447 and I was experiencing the sidenav.js error (only on Firefox). This fix works great for FF, will see if it affects IE users at all

**Comment by dmxd5** [comment]
This issue occurs after I delete a page. Clearing all the cms cache and doing Chrome hard reload fixes it for me.

**Comment by nizzac** [comment]
> 
> 
> It's too stupid to be true... 😄
> @tobias-kuendig - your's FF bug could be fixed with single line of code. If you could test this out would be awesome ;)
> 
> File: `october.sidenav.js`
> Change this
> 
> ```
> $(document).ready(function(){
>         $('[data-control="sidenav"]').sideNav()
> })
> ```
> 
> To this:
> 
> ```
> $(window).on('load', function(){
>         $('[data-control="sidenav"]').sideNav()
> })
> ```
> 
> Cant' reproduce in the latest dev build the same issue with chrome and new users... Hm...Any testers to help me out? :)

This fixed this issue in Firefox for me and didn't affect Chrome or IE.

Internet Explorer Version 11.253.17763.0            Works                            
Chrome Version 73.0.3683.86                         Works
Firefox Quantum Version 66.0.2                      Works

**Comment by mjauvin** [comment]
Fixes my issue in QuteBrowser (based on chromium), finally!

**Comment by damianlewis** [comment]
> It's too stupid to be true... 😄
> @tobias-kuendig - your's FF bug could be fixed with a single line of code. If you could test this out would be awesome ;)
> 
> File: `october.sidenav.js`
> Change this
> 
> ```
> $(document).ready(function(){
>         $('[data-control="sidenav"]').sideNav()
> })
> ```
> To this:
> 
> ```
> $(window).on('load', function(){
>         $('[data-control="sidenav"]').sideNav()
> })
> ```
> Cant' reproduce in the latest dev build the same issue with chrome and new users... Hm...Any testers to help me out? :)

I've tried this fix again and can confirm that it doesn't work for OctoberCMS build 447 when using IE 11.0.9600.19266 on Windows 7 Enterprise.

**Comment by w20k** [comment]
@damianlewis do you have any errors?

**Comment by damianlewis** [comment]
@w20k after adding the `<meta http-equiv="x-ua-compatible" content="IE=edge">` meta tag, these are the errors from IE 11 when loading the /backend/cms page.
```
SCRIPT5007: Unable to get property 'setActiveItem' of undefined or null reference
File: october-min.js, Line: 996, Column: 6
SCRIPT5007: Unable to get property 'setActiveItem' of undefined or null reference
File: jquery.min.js, Line: 2, Column: 31040
```

This is the error when clicking on a page link in the CMS section.
```
SCRIPT5007: Unable to get property 'goTo' of undefined or null reference
File: october.cmspage.js, Line: 89, Column: 10
```

**Comment by daftspunk** [comment]
This should be fixed by 288d9543afb5f856a03f03b68dca96e4ed1f410a available in Build 449+

**Comment by ayumihamsaki** [comment]
The HTTP Header:

```html
<meta http-equiv="x-ua-compatible" content="IE=edge">
```

Is a dead HTTP Header and Microsoft have dropped support for it a few years ago. They say not to use it by the way.

Likewise with the chrome one:

```html
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
```

I wouldn't recommend to use it.
