### ISSUE TITLE
Flickering on Media manager files after latest update

### ISSUE THREAD

**Issue by haralake** [octobercms/october#4601]
- OctoberCMS Build: ### 458
- PHP Version: 7.3
- Database Engine: MySQL
- Plugins Installed: 

### Description:
Flickering on Media manager files. If you open Media manager folder with a lot of files and try to scroll down to the last you will see flickering, and you are unable to select any of the files. Something i noticed is that if you resize browser window it stops flickering and is working fine. You can see this issue bellow:

![Screenshot](http://ketikidis.com/themes/ketikidis-identity/assets/images/issues/flickering.gif)

### Steps To Reproduce:
Just open Media manager
Create folder and upload many images
Try to scroll down to the latest
Flickering!

**Comment by bennothommo** [comment]
This has been reported by a few users on Slack, so bumping up the priority.

**Comment by haralake** [comment]
Thank you @bennothommo . If you have a lot files is impossible to work with media manager so the only quick solution for now is to downgrade.

**Comment by roojai** [comment]
I'm having this issue on a number of sites - whats the best way to downgrade?

**Comment by bennothommo** [comment]
@roojai If you upgraded via Composer, you can change the October dependencies in `composer.json` in your root folder to the following:
```
        "october/rain": "1.0.455",
        "october/system": "1.0.455",
        "october/backend": "1.0.455",
        "october/cms": "1.0.455",
```

**Comment by roojai** [comment]
Thanks @bennothommo but not really sure how to do that. 

I use 1pilot to manage multiple site upgrades, or I just use the backend plugin updates button.

The "resize browser" fix works well for now

**Comment by panakour** [comment]
![Peek 2019-09-06 10-56](https://user-images.githubusercontent.com/12927166/64411304-8c0ede80-d095-11e9-9c8c-b81b37a759d6.gif)

**Comment by w20k** [comment]
@bennothommo will look at it as well!

**Comment by acasar** [comment]
Same issue here... I thought it was only me :)

**Comment by w20k** [comment]
@bennothommo I know what component causes the issue will dig dipper.
`scrollpad` (.scrollpad-scrollbar >  .drag-handler`) -> is the culprit here.

**Comment by LukeTowers** [comment]
@w20k in case it helps I've seen this happen on Facebook too just now, except much more aggressively and vertically instead of horizontally on the latest chrome.

**Comment by pavelmgn** [comment]
temporary fix
```
div[data-control="media-manager"] .control-scrollpad {
	position: relative;
    max-height: 500px;
    overflow: hidden;
}
```

**Comment by bennothommo** [comment]
I personally have been unable to replicate this on Linux running Chrome 76 and Firefox 69.

Is this happening on a particular browser or OS?

**Comment by pavelmgn** [comment]
@bennothommo i have windows 10, chrome ver 76.0.3809.132 (Official build), (64 bit). actual problem

**Comment by roojai** [comment]
Im on the same set up as @pavelmgn. @bennothommo I have noticed that the problem does not occur in media manager itself, but when you access media through a form from another plugin.

**Comment by bennothommo** [comment]
@pavelmgn @roojai would either of you be willing to test it with smooth scrolling disabled in your browser and see if it makes a difference?

**Comment by ayumihamsaki** [comment]
I use Google Canary and I know the last few months I have seen loads of scrolling bugs and even reported it to Google.

I would be interested to know if you install Google Canary, found here: https://www.google.com/chrome/canary/

And see if the issue still continues? As Google Canary V78 has fixed the scrolling bugs (most of them).

And this issue I saw a few months back when Google Canary was using V76.

**Comment by pavelmgn** [comment]
@bennothommo no difference =( With smooth scrolling disabled, the same thing happens.

**Comment by roojai** [comment]
Seems more Chrome related than OctoberCMS, I am having the same problem on a site that is on build 447

**Comment by bennothommo** [comment]
@roojai I'm leaning towards that too, given what I've read about these types of issues with Chrome (I still haven't been able to replicate myself). Just to narrow this issue down further, can you test it with Firefox and let me know if that exhibits the same issue?

**Comment by ayumihamsaki** [comment]
@bennothommo When I reported this issue to Chrome 2 months ago the Chrome team told me it's an issue with the "hardware acceleration" inside Chrome. Maybe people can try disabling it.

**Comment by ayumihamsaki** [comment]
@bennothommo When I reported this issue to Chrome 2 months ago the Chrome team told me it's an issue with the "hardware acceleration" inside Chrome. Maybe people can try disabling it.

Not sure if this was the tag:

```
chrome://flags/#disable-accelerated-video-decode
```

p.s. for me it didn't work on a windows 10. But others said it worked on a MAC.

**Comment by bennothommo** [comment]
Thanks @ayumihamsaki. @roojai @pavelmgn, could you try @ayumihamsaki's suggestion and see if it makes a difference?

**Comment by roojai** [comment]
I have tested turning off hardware acceleration and there was no change - I am still getting the flashing bug.

I tested MS Edge and no flashing bug evident there.

I tested Google Canary and no flashing bug evident on that browser.

So problem seems to be Chrome build Version 76.0.3809.132 (Official Build) (64-bit) on Windows

**Comment by drmzio** [comment]
Happens on Chrome 76 for Mac too. Other browsers aren't affected.

**Comment by bennothommo** [comment]
Cheers all. I'm happy to chalk this up to a Chrome issue. Please let me know if this is affecting a version of Chrome after 76, or another browser, and I'll re-open.

**Comment by Grawl** [comment]
macOS, Chrome 76.0.3809.132
![ezgif-2-fc9681c20f78](https://user-images.githubusercontent.com/846774/64595455-518aa600-d3f5-11e9-826a-a06bc07a4b58.gif)

**Comment by bennothommo** [comment]
@Grawl Please see https://github.com/octobercms/october/issues/4601#issuecomment-529295047

**Comment by Grawl** [comment]
As a workaround I just removed `div[data-control="media-manager"] .control-scrollpad{position:absolute;left:0;top:0}` from `modules/backend/widgets/mediamanager/assets/css/mediamanager.css` and now Media Manager modal window have full window scroll instead of files list/grid inner scroll.

**Comment by anastasiauz** [comment]
Same problem on MacOS, both in Safari and in Chrome, and in Chrome 76 on LinuxOS Ubuntu 16.04, October 458

**Comment by pavelmgn** [comment]
@anastasiauz https://github.com/octobercms/october/issues/4601#issuecomment-529076923
;) @Grawl If the number of entries is 200? Do you want to see a preview of the bottom picture, scroll down, then come back up? If the image turns out to be wrong, will you come back down again, etc.?

**Comment by bennothommo** [comment]
@anastasiauz I closed it because it was a problem introduced by Chrome 76, which we have no control over. I've had no luck with replicating it myself. We've had reports that the issue is no longer there with Chrome 78 which is still in testing.

If you can demonstrate the issue consistently occurring with a current version of Safari or Firefox, I'll be happy to reopen.

**Comment by anastasiauz** [comment]
@bennothommo I cannot show it because I fixed it for the client's site - the client wasn't happy. And I don't have a Mac. Sorry, no evidence ...

**Comment by bennothommo** [comment]
@anastasiauz for what it's worth, it's been reported that this same issue has affected Facebook too, so it's not just affecting October :)

**Comment by Grawl** [comment]
How about to use Flexbox for layout? I think it must fix this problem.

**Comment by Grawl** [comment]
@pavelmgn yep, it's a problem with this workaround. You can try to set `position: sticky; top : 0` for `[data-control="preview-sidebar"]`. (I just tried this but with no luck)

**Comment by vangar02** [comment]
We've got a lot of October sites and clients are complaining. But it is indeed a chrome issue.

There's a quick fix. Just paste this in your Settings > Customize Back-End > Styles tab.

`body div[data-control="media-manager"] .control-scrollpad{position:static}`

When chrome fixes this bug, just remove it again.

**Comment by Grawl** [comment]
I just set fixed height for scroll wrapper and got October's scroll behaviour without flickering.

So, full workaround looks like this:

`modules/backend/widgets/mediamanager/assets/css/mediamanager.css`

```diff
-div[data-control="media-manager"] .control-scrollpad{position:absolute;left:0;top:0}
-div[data-control="media-manager"] .scroll-wrapper{position:relative}
+div[data-control="media-manager"] .scroll-wrapper{height:calc(100vh / 3 * 2);}
```

**Comment by roojai** [comment]
'''
body div[data-control="media-manager"] .control-scrollpad{position:static}
'''
Is working for me ok.
'''
div[data-control="media-manager"] .control-scrollpad{position:static}
div[data-control="media-manager"] .scroll-wrapper{height:calc(100vh - 300px)}
'''
Gives me a blank page in media manager

**Comment by Grawl** [comment]
Please tell me what browser you are using to get this issue

**Comment by roojai** [comment]
Sorry, I am using chrome Version 76.0.3809.132 (Official Build) (64-bit) on windows

**Comment by iboved** [comment]
@bennothommo I have just updated my Google Chrome to 77.0.3865.75 version. And I still have the same problem.

**Comment by Farrow** [comment]
Thanks to Grawl for the CSS needed to fix the issue. The backend updates didn't work for me, but the mediamanager.css file updates did.

As a note for others though, you'll also need to update `modules/backend/widgets/mediamanager/assets/less/mediamanager.less`

if you use the October less compiler (like we do for our deployment process). If you don't update the less file then if you run "php artisan october:util compile [assets|less]" then the mediamanger.css file will be overwritten.

```diff
-    .control-scrollpad {
-       position: absolute;
-        left: 0;
-        top: 0;
-    }

    .scroll-wrapper {
-        position: relative;
+        height: calc(~"100vh - 300px");
    }
```

Note that the calc has a ~ in there so that the less compiler doesn't try to evaluate the expression at build time. Without it you end up with the wrong css.

**Comment by LukeTowers** [comment]
@iboved 

> I have just updated my Google Chrome to 77.0.3865.75 version. And I still have the same problem.

It's reported fixed in Chrome 78.

**Comment by Grawl** [comment]
Latest stable is 77

**Comment by LukeTowers** [comment]
@Grawl please try updating to 78 and see if it has been fixed.

**Comment by ayumihamasaki2019** [comment]
@LukeTowers I've read many people's comments on various css fixes, but I really don't agree with anyone here! 

Everyone is complaining about scrolling issues, just to be clear I have updated jQuery mousewheel package found here: https://github.com/octobercms/october/pull/4574

Daftspunk merged it in v460 so I would like to see if people upgrade to v460 and still see this issue or not?

The reason I say this is because several days ago we changed that package to be kinder to scrolling.

I will look deeper over in this issue: https://github.com/octobercms/october/issues/4621

**Comment by ayumihamasaki2019** [comment]
As this issue is with Google Chrome versions 76 and 77 and I have no issue on V79 and previous V78. It would be interesting to see people turn off the smooth scrolling plugin in Google Chrome, to do this us the following code:

```
chrome://flags//#smooth-scrolling
```

Then disable.

Or just install Google canary instead of chrome.

**Comment by ayumihamasaki2019** [comment]
PR submitted.

**Comment by ayumihamasaki2019** [comment]
Ok PR submitted.

There were two issues causing the error, these are as follows:

1. The issue was the `position` using `absolute` and not `sticky`, which caused a forever scrolling action. `Position: sticky` has fixed this issue.

2. The issue here was because the scrollbar javascript in the media manager needs to have the right sidebar displayed and the css was using `display: none`, switching it over to `opacity: 0` allows the javascript to scroll the container. If you set the display to none you will see the `data-visible` attribute keep trying to set it to `true` and the screen starts flickering! The right sidebar in the media manager is the place where the media file previews are displayed.

Please can some people test out my PR and shout at me - when needed, pr is here: https://github.com/octobercms/october/pull/4632

**Comment by Grawl** [comment]
Just checked for updates and it's still 77

**Comment by SebastiaanKloos** [comment]
Chrome update 78 fixed it for me

**Comment by haralake** [comment]
I confirm that chrome v.78 has fixed this issue

**Comment by LukeTowers** [comment]
Great, will leave it open until 460 is released at least

**Comment by SebastiaanKloos** [comment]
@LukeTowers Issue still fixed with `78.0.3904.108`

**Comment by ayumi-cloud** [comment]
⚠️Warning ⚠️ As of December 2019 there is an issue in the Firefox browser with the media manager, see video of the error here: https://youtu.be/Rlq9R3WIDfQ

If you or your clients use Firefox, I suggest adding this commit to fix it: 1e449c8

🔥🔥🔥
