### ISSUE TITLE
Extend marketplace bundles with the products developed by 3d party vendors

### ISSUE THREAD

**Issue by lautsevich** [octobercms/october#5103]
There's no possibility to add to the bundle plugin or theme which belongs to other vendors. There are only your products in the select box. 

![image](https://user-images.githubusercontent.com/196445/83523471-edf85980-a4ea-11ea-8076-0309d80063d2.png)

It would be great to provide the ability to add 3d party vendors. We believe it will push marketplace purchases, vendors collaboration, and October CMS revenue forward, as well. Let me explain, please.

As we're from the Russian-speaking community, we know the local market and local customers' habits well. There's a huge monopolist in Russia called [Bitrix](https://www.1c-bitrix.ru). Let's check its popularity among web design agencies in the CMS [rating](https://cmsmagazine.ru/cms/) by cmsmagazine.ru.

![image](https://user-images.githubusercontent.com/196445/83524648-90fda300-a4ec-11ea-8efd-f0c89990a78a.png)

Not the last reason of a such popularity is the existence of ready-made websites based on [1C-Bitrix](https://www.1c-bitrix.ru). There's a 3d party vendor [Aspro](https://aspro.ru), who sells prepacked 1C-Bitrix bundles for a wide range of businesses ([ecommerce](https://aspro.ru/marketplace/ecommerce/), [corporate websites](https://aspro.ru/marketplace/corporate/)). And such a product is very popular among the customers. It's much cheaper and faster to launch a new website, especially you have a limited budget. Customers ask developers to customize these bundles after a while. This a good alternative to SaaS, which became more popular day by day.

We sell two bundles as ready-made websites:
- [Sneakers Shop for Shopaholic](https://octobercms.com/bundle/lovata-sneakers-shop-bundle-for-shopaholic)
- [Sneakers Shop Pro for Shopaholic](https://octobercms.com/bundle/lovata-sneakers-shop-pro-bundle-for-shopaholic)

We'd love to include in such bundles 3d party plugins to extend the functionality of the bundle. Such plugin vendors will get more purchases in this case. Besides, we receive a lot of requests from third-party vendors regarding their wish to sell their themes with Shopaholic plugins. Exactly what we do by ourselves.

So, we believe such functionality will boost the marketplace to the new high. This's a win-win-win proposal (developers, customers, October CMS).

I want to ask the community, how do you feel about that? Please, rate this comment with 👍️ or 👎️ and share your thoughts.

**Comment by lautsevich** [comment]
The list of important things that should be discussed:
- restrictions options to disable the ability to add a product to a 3rd party bundles;
- options to sell 3rd party product with on a discounted price as part of a bundle;
- warranty and support for the 3rd party product sold as a part of a bundle.

**Comment by RomainMazB** [comment]
I'm not selling any product on the marketplace yet so my mind may not reflect the reality.

As I know: free product can be "added" to a bundle, just by require them in the plugin or theme. So the problem comes only for the paid products.

If so I see both good improvements and problems here:
### Improvements
- It will give some visibility for less-popular plugins which could be added in some popular plugins
- It will create as you said  more social between the marketplace vendors which could be great for all, including October (already said but I totally agree this part)

### Problems
- What should happen when a "coupon" is used? Such as the SHOPA10K actually? Will the other vendors price also be decreased without their agreement?
- As you mentioned, the support of the 3rd part plugin is hard. What happens if the 3rd vendor stop the support? Will you provide a support from yourself to the already sold bundles?

This was my think about that stuff I don't fully understand yet.

**Comment by LukeTowers** [comment]
As @RomainMazB said, you can already include free plugins through dependencies. Paid plugins not by the bundle author would be incredibly complex to implement support for because you would get into incredibly complex situations around revenue splitting of bundle sales, handling discounts on the bundle as a whole as well as any discounts that a third party author might have on their product. 

Personally, I'm just not convinced its worth the added code & accounting complexity.

**Comment by lautsevich** [comment]
@RomainMazB, thx for your opinion. As for free plugins, you right they can be added as requirements to the theme and it should be working. But there's a huge bug I've found and described in [here](https://github.com/octobercms/october/issues/4728#issuecomment-558671387).

As for the problems you've mentioned. Thx for the points, I'll add it to the commend above.

**Comment by lautsevich** [comment]
@RomainMazB, and as for coupons. There's no possibility to apply a coupon to a bundle while you purchase it.

**Comment by lautsevich** [comment]
@RomainMazB, @LukeTowers, as for warranty. I've never purchased a bundle by myself, I just sell bundles. =)) As a merchant I see the purchase of a bundle like that

![image](https://user-images.githubusercontent.com/196445/83548431-6c192800-a50c-11ea-90f1-2a7b79074c6f.png)

I mean, I see 7 purchases of paid plugins included in the "Sneakers Shop for Shopaholic" bundle. I don't have an invoice for some of our customers to check how the purchase looks for them. I'll get it tomorrow.

Anyway IMO bundle page can inform a customer that bundle includes products of a 3rd party vendor, so the warranty and support for that part of a bundle are handled by its developer. And the customer will get a separate invoice for each 3rd party product he/she has purchased.

**Comment by LukeTowers** [comment]
The problem still stands when it comes to how to split the revenue with the third party author. If they're charging $50 for their plugin, and you're charging $20 for your bundle, how would they get paid? And even if you're charging $60 for your bundle, what, that means you're only getting $10 for everything you added to it?

It opens up a huge can of worms when it comes to how to split the revenue of the sales, not only from a coding perspective but also from an accounting perspective.

**Comment by lautsevich** [comment]
> If they're charging $50 for their plugin, and you're charging $20 for your bundle

The price field should be restricted to the min value of the sum of the 3rd party bundles.

> And even if you're charging $60 for your bundle, what, that means you're only getting $10 for everything you added to it?

Yep. It's the merchant's responsibility.

@LukeTowers, you should know how things work. I mean setting the price value for a bundle. Let me show to others.

To set the discount to a single product, you should you can set the discount percentage value for a coupon.

![image](https://user-images.githubusercontent.com/196445/83562216-dbe5dd80-a521-11ea-8398-83ac8aa6daa1.png)

To set the discount to a bundle, you should decrease the price of some product included

![image](https://user-images.githubusercontent.com/196445/83561141-03d44180-a520-11ea-9caf-00d525a92056.png)

In the Sneakers Shop for Shopaholic bundle, I've decreased the price for the theme included.

![image](https://user-images.githubusercontent.com/196445/83560907-9c1df680-a51f-11ea-8e5b-13588a55c74b.png)

**Comment by lautsevich** [comment]
Ahaha! I just clicked to the Approved link and saw this modal

![image](https://user-images.githubusercontent.com/196445/83562765-cc1ac900-a522-11ea-88b8-5fac6612000f.png)

I've never used this functionality! Anyway, there can be a restriction to change 3rd party vendor price value. Or there can be an input to apply a personal coupon to discount the value.

**Comment by lautsevich** [comment]
Some thoughts.

The list of the bundle products including 3rd party plugin.

![image](https://user-images.githubusercontent.com/196445/83569748-a646f180-a52d-11ea-89e7-b92a5d5e1462.png)

Edit bundle product modal without the ability to change 3rd party product price.

![image](https://user-images.githubusercontent.com/196445/83568993-8236e080-a52c-11ea-8faa-40104ecb560d.png)

Edit bundle product modal with the ability to change 3rd party product price using a personal coupon.

![image](https://user-images.githubusercontent.com/196445/83569519-481a0e80-a52d-11ea-89ea-6c48f112c513.png)

Make plugin available to add to the 3rd party bundles.

![image](https://user-images.githubusercontent.com/196445/83570448-bb705000-a52e-11ea-8a8c-04e65c9283c8.png)

**Comment by LukeTowers** [comment]
Hmm, not bad for UX @lautsevich, there's still the complexity of actually implementing it and dealing with the accounting side of it. I'll pass it along to @daftspunk though.

**Comment by lautsevich** [comment]
Great, thx!

**Comment by lautsevich** [comment]
BTW, AFAIK this functionality has been planned for the first release of the bundles' functionality. We've discussed it with @alekseybobkov for more than one year ago.

**Comment by LukeTowers** [comment]
Yeah, I talked to Sam and it's still in the plan for future functionality to be added. No promises on when it'll be added though, @alekseybobkov's a busy guy.

**Comment by lautsevich** [comment]
I know, I know. I've opened this issue to discuss the idea with the community first of all.

**Comment by LukeTowers** [comment]
There's not much to discuss AFAIK, it's a planned feature, and as always when it comes to the marketplace there is no guaranteed timeline of when it will be completed. If anyone has any specific problems or suggestions they can think of then they're welcome to add them to the issue of course, but no guarantee they'll be implemented. Voting on it also won't speed it up 😉
