### ISSUE TITLE
File upload error in build 469

### ISSUE THREAD

**Issue by Dabani** [octobercms/october#5410]
- OctoberCMS Build: 469 
- PHP Version: 7.2.12
- Database Engine: InnoDB
- Plugins Installed: Slideshow By Florent SCHILDKNECHT version 1.0.8, RainLab.Blog version 1.4.3

### Description:

- The following error appear when I upload images (even smaller images) to slideshow : 
- Upload error "Return value of Symfony\Component\HttpFoundation\File\UploadedFile::parseFilesize() must be of the type integer, float returned" on line 282 of C:\xampp\htdocs\supermarket\vendor\symfony\http-foundation\File\UploadedFile.php
- I've realized that the Slideshow plugin is still correctly working with build 464, and it works in version 469 if I replace the content of the file C:\xampp\htdocs\supermarket\vendor\symfony\http-foundation\File\UploadedFile.php with the content of the same file of the version 464.
- The same problem occurs when I try to upload a featured image in the RainLab Blog plugin, as described above. So the problem is not the plugin, but the version compatibility.

### Steps To Reproduce:

I'm simply requesting to check the compatibility of new versions OctoberCMS builds, and hopefully the bug will be fixed as soon as possible.

**Comment by Eoler** [comment]
> I'm simply requesting to check the compatibility of new versions OctoberCMS builds, and hopefully the bug will be fixed as soon as possible.

This is probably fixed in 471.

**Comment by LukeTowers** [comment]
@Dabani looks related to https://github.com/symfony/symfony/issues/34508 and https://github.com/symfony/symfony/pull/34516, try updating to 471. Also note that 1.1 is the supported version of October right now, so if you want further help on this you'll have to confirm that the issue exists on v1.1.1 through composer.

**Comment by Dabani** [comment]
**Upload error
"Return value of Symfony\Component\HttpFoundation\File\UploadedFile::parseFilesize() must be of the type integer, float returned" on line 282 of C:\xampp\htdocs\uploadtest\vendor\symfony\http-foundation\File\UploadedFile.php**

This to confirm the issue in version 1.1.1, I installed a fresh new OctoberCMS project and the RainLab Blog plugin, the featured image upload still failing in the latest version!

Can someone imagine all of the plugins involving file upload that are suffering from this issue?

Please, once again check in deep the version compatibility with the already existing plugins...

**Comment by LukeTowers** [comment]
>  I installed a fresh new OctoberCMS project

How did you install it? Also, what is the size of the image you're trying to upload?

**Comment by Dabani** [comment]
Hello Luke, I always install my October projects via composer, and I'm using the latest version of composer (version 2.0). The images I'm uploading are relatively small (30k).

**Comment by LukeTowers** [comment]
Run this command in your project root and let me know what version it reports: `composer show october/rain`

**Comment by Dabani** [comment]
Hello Luke, it reports  version 1.1.1

Find below the whole report

$ composer show october/rain
name     : october/rain
descrip. : October Rain Library
keywords : cms, october, rain
**versions : * v1.1.1**
type     : library
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#l
icenseText
homepage : http://octobercms.com
source   : [git] https://github.com/octobercms/library.git 717b39b3daee566e1253b
dde30754625b63946fe
dist     : [zip] https://api.github.com/repos/octobercms/library/zipball/717b39b
3daee566e1253bdde30754625b63946fe 717b39b3daee566e1253bdde30754625b63946fe
path     : C:\xampp\htdocs\uploadtest\vendor\october\rain
names    : october/rain

support
source : https://github.com/octobercms/library/tree/v1.1.1

autoload
files
psr-4
October\Rain\ => src/

requires
doctrine/dbal ^2.6
erusev/parsedown-extra ~0.7
ext-ctype *
ext-curl *
ext-dom *
ext-fileinfo *
ext-gd *
ext-json *
ext-libxml *
ext-mbstring *
ext-openssl *
ext-pdo *
ext-zip *
laravel/framework ~6.0
laravel/tinker ~2.0
league/csv ~9.1
linkorb/jsmin-php ~1.0
nesbot/carbon ^2.0
php >=7.2
scssphp/scssphp ~1.0
symfony/yaml ^3.4
twig/twig ~2.0
wikimedia/less.php ~2.0

requires (dev)
dms/phpunit-arraysubset-asserts ^0.1.0
illuminate/cache ^6.0
illuminate/database ^6.0
illuminate/encryption ^6.0
illuminate/events ^6.0
illuminate/filesystem ^6.0
illuminate/log ^6.0
illuminate/mail ^6.0
illuminate/pagination ^6.0
illuminate/queue ^6.0
illuminate/redis ^6.0
illuminate/routing ^6.0
illuminate/support ^6.0
illuminate/validation ^6.0
illuminate/view ^6.0
meyfa/phpunit-assert-gd ^2.0.0
mockery/mockery ~1.3.3|^1.4.2
php-parallel-lint/php-parallel-lint ^1.0
phpunit/phpunit ^8.4|^9.3.3
squizlabs/php_codesniffer 3.*

suggests
ext-PDO_ODBC Required to use databases accessed through ODBC drivers
ext-pdo_dblib Required to use MS SQL Server databases
ext-pdo_mysql Required to use MySQL databases
ext-pdo_pgsql Required to use PostgreSQL databases
ext-pdo_sqlite Required to use SQLite databases

**Comment by LukeTowers** [comment]
@Dabani try manually making the changes from https://github.com/symfony/symfony/pull/39633/files

**Comment by Dabani** [comment]
Hello Luke thanks, the changes you made has fixed the issue!

**Comment by LukeTowers** [comment]
Fixed by https://github.com/symfony/symfony/commit/3257d4c2ed919b125152626cf15f44f2cc11a1f1
